#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x89EFD588E975D6DF (rbtcollins@hp.com)
#
Name     : deprecated-linecache2
Version  : 1.0.0
Release  : 45
URL      : http://pypi.debian.net/linecache2/linecache2-1.0.0.tar.gz
Source0  : http://pypi.debian.net/linecache2/linecache2-1.0.0.tar.gz
Source99 : http://pypi.debian.net/linecache2/linecache2-1.0.0.tar.gz.asc
Summary  : Backports of the linecache module
Group    : Development/Tools
License  : Python-2.0
Requires: deprecated-linecache2-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pbr-legacypython
BuildRequires : setuptools-legacypython

%description
A backport of linecache to older supported Pythons.
>>> import linecache2 as linecache

%package legacypython
Summary: legacypython components for the deprecated-linecache2 package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-linecache2 package.


%package python
Summary: python components for the deprecated-linecache2 package.
Group: Default

%description python
python components for the deprecated-linecache2 package.


%prep
%setup -q -n linecache2-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554321862
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
